"""
sector_mapper.py — Mapping sectoriel des émetteurs (OBLIG_ORDN)
Matching exact sur la colonne PREFERREDNAMEISSUER.
Émetteur absent du mapping → 'AUTRES'.
"""
from __future__ import annotations

BANQUES_EXCLUES: set[str] = {
    'ATW E', 'BCP E', 'CIH E', 'BOA', 'CAM E', 'CDM', 'CDG E',
    'CFG BANK', 'CFC', 'CFM', 'SAHAM FINANCES', 'BMCI',
    'BMCI LEASI', 'AL BARID BANK E', 'CREDIPER FT',
}

SECTEUR_MAP: dict[str, str] = {
    # ENERGIE
    'ONEE': 'ENERGIE', 'TAQA MOROCCO': 'ENERGIE', 'MASEN': 'ENERGIE',
    'FEC': 'ENERGIE', 'LYDEC': 'ENERGIE', 'SAMIR': 'ENERGIE',
    'SEDM': 'ENERGIE', 'TMPA': 'ENERGIE', 'AFRIQUIA GAZ': 'ENERGIE',
    'AFIQUIA LUB': 'ENERGIE', 'MAGHREB OXYGENE': 'ENERGIE',
    'PHOSPH BOUCRAA': 'ENERGIE',
    # BTP
    'TGCC': 'BTP', 'JET CONTRACTORS': 'BTP', 'ADI': 'BTP',
    'SETTAVEX': 'BTP', 'CMGP GROUP': 'BTP', 'ASSIFILL BUILD': 'BTP',
    'BUILDING LOGIST': 'BTP', 'NADOR WEST MED': 'BTP',
    # CIMENTERIE
    'HOLCIM MAROC': 'CIMENTERIE', 'CIMAT': 'CIMENTERIE',
    # IMMOBILIER
    'CGI': 'IMMOBILIER', 'ALLIANCES DARNA': 'IMMOBILIER',
    'DOUJA PROM ADD': 'IMMOBILIER', 'AL OMRANE': 'IMMOBILIER',
    'IMMOLOG': 'IMMOBILIER', 'ARADEI CAPITAL': 'IMMOBILIER',
    'BEST REAL ESTAT': 'IMMOBILIER', 'HAYAN IMMO SA': 'IMMOBILIER',
    'PALME DEV': 'IMMOBILIER', 'CMR LSTONE': 'IMMOBILIER',
    'Immorent SC': 'IMMOBILIER', 'RDS': 'IMMOBILIER',
    # TRANSPORT
    'ONCF': 'TRANSPORT', 'ONDA': 'TRANSPORT', 'CTM SA': 'TRANSPORT',
    'COMANAV': 'TRANSPORT', 'TANGER MED  SA': 'TRANSPORT',
    'TMSA': 'TRANSPORT', 'ANP': 'TRANSPORT', 'ADM': 'TRANSPORT',
    'MEDIACO MAROC': 'TRANSPORT', 'CMT': 'TRANSPORT',
    # TELECOM
    'MEDI TELCOM SA': 'TELECOM', 'IAM': 'TELECOM',
    # CHIMIE / MINES
    'OCP SA': 'CHIMIE / MINES', 'OCP NUTRICROPS': 'CHIMIE / MINES',
    'MANAGEM': 'CHIMIE / MINES',
    # AGRO-ALIMENTAIRE
    'OULMES': 'AGRO-ALIMENTAIRE', 'UNIMER': 'AGRO-ALIMENTAIRE',
    'AFRICA FEED FOOD': 'AGRO-ALIMENTAIRE',
    'SOMACOVAM': 'AGRO-ALIMENTAIRE', 'MUTANDIS SCA': 'AGRO-ALIMENTAIRE',
    'ZALAGH HOLDING': 'AGRO-ALIMENTAIRE',
    # SIDERURGIE
    'MAGHREB STEEL': 'SIDERURGIE',
    # SANTE
    'AKDITAL': 'SANTE',
    # TOURISME
    'RISMA SA': 'TOURISME', 'MADAEF': 'TOURISME',
    # GRANDE DISTRIBUTION
    'LABEL VIE': 'GRANDE DISTRIBUTION',
    'MARJANE HOLDING': 'GRANDE DISTRIBUTION',
    'RETAIL HOLDING': 'GRANDE DISTRIBUTION',
    # HOLDING
    'AL MADA': 'HOLDING', 'HOLMARCOM FIN CO': 'HOLDING',
    'FINANCECOM': 'HOLDING', 'FINANCIER SEC': 'HOLDING',
    'O CAPITAL GROUP': 'HOLDING', 'GROUP INVEST SA': 'HOLDING',
    'GARAN': 'HOLDING', 'Hold GENE EDU': 'HOLDING',
    # LEASING
    'MAGHREBAIL': 'LEASING', 'MA LEASING': 'LEASING',
    # CREDIT CONSO
    'WAFASALAF': 'CREDIT CONSO', 'TASLIF': 'CREDIT CONSO',
    # ASSURANCE
    'SAHAM': 'ASSURANCE',
    # MICROFINANCE
    'JAIDA': 'MICROFINANCE', 'SFI': 'MICROFINANCE',
    # PARA-PUBLIC
    'SCIF': 'PARA-PUBLIC', 'ORMVAD': 'PARA-PUBLIC',
    'COMMUNE AGADIR': 'PARA-PUBLIC', 'BEST FINANCIERE': 'PARA-PUBLIC',
    'AGRI CAPITAL': 'PARA-PUBLIC',
    # AUTOMOBILE
    'RCI': 'AUTOMOBILE', 'UNIVERS MOTORS': 'AUTOMOBILE',
    'AUTO NEJMA': 'AUTOMOBILE', 'OD MAROC': 'AUTOMOBILE',
    # EDUCATION
    'Univ Mohammed VI': 'EDUCATION',
    # TEXTILE
    'DISTRA-S.A': 'TEXTILE', 'MCM': 'TEXTILE',
    # INDUSTRIE
    'CMB PLA MAROC': 'INDUSTRIE', 'TC3PC': 'INDUSTRIE',
    'FINAN HATT': 'INDUSTRIE',
}


def detect_sector(issuer: str) -> str:
    """Retourne le secteur d'un émetteur, ou 'AUTRES' si inconnu."""
    return SECTEUR_MAP.get(str(issuer).strip(), "AUTRES")


def is_bank(issuer: str) -> bool:
    """Retourne True si l'émetteur est une banque à exclure."""
    return str(issuer).strip() in BANQUES_EXCLUES
